services:
  - type: web
    name: gui-playground
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "5000"
    healthCheckPath: "/"
    logStreamingEnabled: true
